lang: es 
website:
  cookie-consent: true

project:
  type: book  
  output-dir: docs  

  
book:
  title: "Ecosistema libre para ciencia"
  navbar:
    search: True
  sidebar:
    menu: True
    collapse-level: 1
    border: true
    # logo: img/logo_ier.png
  page-footer:
    # left:  Logo  por  Dnu72, [CC BY-SA 4.0](<https://creativecommons.org/licenses/by-sa/4.0>), via Wikimedia Commons.
    center: "[Repositorio](https://github.com/altamarmx/ecosistema-libre-ciencia)"
    right: Construido con [Quarto](https://quarto.org/).
    background: "#f8f9fa"
  repo-url: https://github.com/altamarmx/ecosistema-libre-ciencia/
  chapters:
    - index.qmd 
    - qmds/foss.qmd
    - qmds/ecosistema.qmd 
    - qmds/escritura-cientifica.qmd
    - qmds/quarto.qmd
    - qmds/git.qmd
    # - creditos.qmd
format:
  html:
    theme: 
      light: spacelab
      dark: slate
    code-link: true